/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as CampusSlugRouteImport } from './routes/campus.$slug'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const CampusSlugRoute = CampusSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CampusRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admissions': typeof AdmissionsRoute
  '/campus': typeof CampusRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/notices': typeof NoticesRoute
  '/students': typeof StudentsRoute
  '/campus/$slug': typeof CampusSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admissions': typeof AdmissionsRoute
  '/campus': typeof CampusRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/notices': typeof NoticesRoute
  '/students': typeof StudentsRoute
  '/campus/$slug': typeof CampusSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/administration': typeof AdministrationRoute
  '/admissions': typeof AdmissionsRoute
  '/campus': typeof CampusRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/notices': typeof NoticesRoute
  '/students': typeof StudentsRoute
  '/campus/$slug': typeof CampusSlugRoute
  '/courses/$slug': typeof CoursesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/administration'
    | '/admissions'
    | '/campus'
    | '/contact'
    | '/courses'
    | '/notices'
    | '/students'
    | '/campus/$slug'
    | '/courses/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/administration'
    | '/admissions'
    | '/campus'
    | '/contact'
    | '/courses'
    | '/notices'
    | '/students'
    | '/campus/$slug'
    | '/courses/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/administration'
    | '/admissions'
    | '/campus'
    | '/contact'
    | '/courses'
    | '/notices'
    | '/students'
    | '/campus/$slug'
    | '/courses/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdministrationRoute: typeof AdministrationRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusRoute: typeof CampusRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  NoticesRoute: typeof NoticesRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/campus/$slug': {
      id: '/campus/$slug'
      path: '/$slug'
      fullPath: '/campus/$slug'
      preLoaderRoute: typeof CampusSlugRouteImport
      parentRoute: typeof CampusRoute
    }
  }
}

interface CampusRouteChildren {
  CampusSlugRoute: typeof CampusSlugRoute
}

const CampusRouteChildren: CampusRouteChildren = {
  CampusSlugRoute: CampusSlugRoute,
}

const CampusRouteWithChildren =
  CampusRoute._addFileChildren(CampusRouteChildren)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdministrationRoute: AdministrationRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusRoute: CampusRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  NoticesRoute: NoticesRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
